import {
  Square,
  Box,
  DoorOpen,
  Trash2,
  Type,
  Ruler,
} from 'lucide-react';
import type { TileTypeConfig, Translations } from './types';

export const GRID_SIZE = 40;
export const CELL_SIZE = 20;
export const MAX_HISTORY = 50;

export const COLORS = [
  '#3b82f6',
  '#ef4444',
  '#10b981',
  '#f59e0b',
  '#8b5cf6',
  '#ec4899',
  '#64748b',
  '#ffffff',
];

export const TRANSLATIONS: Record<'en' | 'ja', Translations> = {
  en: {
    title: 'Colony Planner',
    subtitle: 'Grid Layout Simulator',
    undo: 'Undo',
    reset: 'Reset',
    gridFocus: 'Grid Focus',
    construction: 'Construction',
    utility: 'Utility',
    eraser: 'Eraser',
    floor: 'Floor',
    wall: 'Wall',
    door: 'Door',
    object: 'Object',
    addLabel: 'Add Label',
    ruler: 'Ruler',
    resetTitle: 'Clear Design?',
    resetDesc:
      'This will delete all tiles and labels. This action cannot be undone.',
    clearAll: 'Clear Everything',
    cancel: 'Cancel',
    areaDesignation: 'Specify Label Name',
    location: 'Location',
    labelPlaceholder: 'Name...',
    labelClear: 'Clear',
    labelConfirm: 'Confirm',
    simActive: 'SYSTEM ONLINE',
    tip: 'Tip: Floor is placed under objects. Drag walls to draw boundaries.',
    langBtn: '日本語',
    mode: 'Mode',
    penMode: 'Pen',
    gridMode: 'Grid',
    width: 'W',
    height: 'H',
    color: 'Color',
    memoTitle: 'Notepad',
    memoPlaceholder: 'Build plans...',
  },
  ja: {
    title: 'Colony Planner',
    subtitle: '汎用レイアウト・プランナー',
    undo: '元に戻す',
    reset: 'リセット',
    gridFocus: 'グリッド強調',
    construction: '建築ツール',
    utility: 'ユーティリティ',
    eraser: '消しゴム',
    floor: '床',
    wall: '壁',
    door: 'ドア',
    object: 'オブジェクト',
    addLabel: 'ラベル追加',
    ruler: 'ルーラー',
    resetTitle: '設計をクリアしますか？',
    resetDesc: 'すべてのタイルとラベルが削除されます。この操作は取り消せません。',
    clearAll: 'すべて削除',
    cancel: 'キャンセル',
    areaDesignation: 'ラベル名を指定',
    location: '座標',
    labelPlaceholder: '名前を入力...',
    labelClear: 'クリア',
    labelConfirm: '確定',
    simActive: 'システム稼働中',
    tip: 'ヒント: 床はオブジェクトを上書きせずに配置されます。壁はドラッグで描画できます。',
    langBtn: 'English',
    mode: 'モード',
    penMode: 'ペン',
    gridMode: 'マス指定',
    width: '幅',
    height: '高さ',
    color: 'カラー',
    memoTitle: 'メモ帳',
    memoPlaceholder: '設計プランをメモ...',
  },
};

export const TILE_TYPES_CONFIG: Record<string, TileTypeConfig> = {
  EMPTY: { id: 'empty', labelKey: 'eraser', color: 'transparent', icon: Trash2 },
  FLOOR: { id: 'floor', labelKey: 'floor', color: '#2d3748', icon: Square },
  WALL: { id: 'wall', labelKey: 'wall', color: '#718096', icon: Box },
  DOOR: { id: 'door', labelKey: 'door', color: '#4a5568', icon: DoorOpen },
  OBJECT: { id: 'object', labelKey: 'object', color: '#3b82f6', icon: Box },
  LABEL: { id: 'label', labelKey: 'addLabel', color: 'transparent', icon: Type },
  RULER: { id: 'ruler', labelKey: 'ruler', color: 'transparent', icon: Ruler },
};
